# Generated by Django 6.0.4 on 2026-04-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_event_image_eventmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMedia',
            new_name='Media',
        ),
    ]
